openapi: 3.0.2
info: 
  title: Mina Curhat App API
  version: 1.0.0
  contact:
    url: https://github.com/Velezer
servers:
  - url: https://mina-curhat-api.herokuapp.com/
paths:
  /:
    get:
      responses:
        200:
          description: OK
