openapi: 3.0.2

info: 
  title: Mina Curhat App API
  version: 1.0.0
  contact:
    name: Velezer
    url: https://github.com/Velezer

externalDocs:
  description: Repository Link
  url: https://github.com/Velezer/mina-curhat-app-api

servers:
  - url: https://mina-curhat-api.herokuapp.com/

paths:
  /:
    get:
      summary: check if server is up
      description: use this endpoint to check if server is up and running
      tags:
        - home
      responses:
        200:
          description: OK

  /api/anonym/login:
    summary: User login as an anonymous
    post:
      tags:
        - anonym
      requestBody:
        required: true
        description: anonym data
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                gender:
                  type: string
                  enum:
                    - male
                    - female
            examples:
              male: 
                value:
                  name: male name
                  gender: male
              female: 
                value:
                  name: female name
                  gender: female
      responses:
        200:
          description: Anonym login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      token:
                        type: string
              example:
                message: success
                token: token
        409:
          description: Conflict, anonym name has taken
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: anonym name has already taken
        400:
          description: Validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        msg:
                          type: string
                        param:
                          type: string
                        location:
                          type: string
  /api/consultants:
    get:
      summary: get all consultants
      description: get all consultants
      tags:
        - consultants
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
              example:
                message: success
                data: [{
                    "_id": "6173d2e7365b7f5cefd2017d",
                    "name": "secretConsultant",
                    "role": "consultant",
                    "gender": "female",
                    "__v": 0
                  }]
  /api/consultants/register:
    post:
      summary: register as a consultants
      description: register as a consultants
      tags:
        - consultants
      requestBody:
        required: true
        description: consultant data
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
                gender:
                  type: string
                  enum:
                    - male
                    - female
                role:
                  type: string
                  enum:
                    - consultant
                    - ustadz
                
      responses:
        201:
          description: consultant created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: created
        409:
          description: consultant already exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: user exist
    
